-- ============================================
-- AIR CONDITIONERS - 25 PRODUCTS
-- Run in Supabase SQL Editor
-- ============================================

INSERT INTO products (id, name, price, original_price, category, description, features, image, rating, reviews, in_stock, badge) VALUES
(201, 'Daikin Cora Series 7.1kW Inverter', 2499, 3124, 'aircon', 'Premium inverter split system with Coanda airflow and intelligent eye sensor.', ARRAY['7.1kW cooling','Inverter tech','Coanda airflow','Intelligent eye','R32 refrigerant','20m range'], '/images/aircon-1.svg', 4.9, 456, true, 'Best Seller'),
(202, 'Mitsubishi Heavy Industries 5.0kW', 1899, 2374, 'aircon', 'High-performance split system with 3D Auto airflow and weekly timer.', ARRAY['5.0kW cooling','3D Auto airflow','Weekly timer','Allergen clear','R32 gas','Whisper quiet'], '/images/aircon-2.svg', 4.8, 312, true, 'Pro Choice'),
(203, 'Fujitsu General 3.5kW Split System', 1199, 1499, 'aircon', 'Compact and efficient split system perfect for bedrooms and small spaces.', ARRAY['3.5kW cooling','Inverter','i-See sensor','Blue fin','Quiet 19dB','Auto restart'], '/images/aircon-3.svg', 4.7, 234, true, null),
(204, 'Samsung WindFree 7.0kW', 2299, 2874, 'aircon', 'WindFree technology eliminates cold draughts for comfortable cooling.', ARRAY['7.0kW cooling','WindFree mode','Digital inverter','Triple protector','R32','WiFi enabled'], '/images/aircon-4.svg', 4.8, 189, true, 'WindFree'),
(205, 'Panasonic Z-Series 5.0kW Inverter', 1799, 2249, 'aircon', 'Nanoe X air purification technology built into premium split system.', ARRAY['5.0kW cooling','Nanoe X tech','ECONAVI sensor','Inverter','Self cleaning','R32 gas'], '/images/aircon-5.svg', 4.7, 167, true, null),
(206, 'Daikin Ururu Sarara 8.0kW', 4299, 5374, 'aircon', 'Flagship model with humidification and fresh air ventilation.', ARRAY['8.0kW cooling','Humidification','Ventilation','Stream purifier','Floor heating','Intelligent eye'], '/images/aircon-6.svg', 4.9, 78, true, 'Premium'),
(207, 'Mitsubishi Electric MSZ-AP25VG 2.5kW', 999, 1249, 'aircon', 'Budget-friendly split system with plasma air filter.', ARRAY['2.5kW cooling','Plasma filter','Dual barrier','Silent mode','Inverter','R32 refrigerant'], '/images/aircon-7.svg', 4.6, 289, true, null),
(208, 'Samsung AR12TX 3.5kW', 1099, 1374, 'aircon', 'Compact split system with Fast Cool and Digital Inverter Boost.', ARRAY['3.5kW cooling','Fast Cool','Inverter Boost','Auto Clean','R32','WiFi ready'], '/images/aircon-8.svg', 4.5, 345, true, null),
(209, 'Fujitsu General 8.0kW ASTG24LXCA', 2799, 3499, 'aircon', 'High-capacity split system for large open-plan living areas.', ARRAY['8.0kW cooling','Super quiet','Inverter','Auto changeover','Wide airflow','R32 gas'], '/images/aircon-9.svg', 4.8, 123, true, null),
(210, 'Panasonic CS/CU-Z25TKR 2.5kW', 899, 1124, 'aircon', 'Entry-level Panasonic split system with AEROWINGS dual airflow.', ARRAY['2.5kW cooling','AEROWINGS','Inverter','Auto mode','24hr timer','R32 refrigerant'], '/images/aircon-10.svg', 4.4, 267, true, null),
(211, 'Daikin Lite Series 2.5kW', 799, 999, 'aircon', 'Affordable Daikin quality for small rooms and bedrooms.', ARRAY['2.5kW cooling','Inverter','Coanda effect','Dry function','Quiet 19dB','R32 gas'], '/images/aircon-11.svg', 4.5, 412, true, 'Value'),
(212, 'Mitsubishi Heavy 2.5kW SRK25ZS-W', 849, 1061, 'aircon', 'Compact wall-mounted split with weekly timer function.', ARRAY['2.5kW cooling','Weekly timer','Allergen clear','Self clean','Inverter','Sleep mode'], '/images/aircon-12.svg', 4.6, 198, true, null),
(213, 'Samsung Good Sleep 3.5kW', 1299, 1624, 'aircon', 'Designed for better sleep with WindFree and AI Auto Cooling.', ARRAY['3.5kW cooling','Good Sleep AI','WindFree','Auto Clean','Triple protector','WiFi'], '/images/aircon-13.svg', 4.7, 156, true, null),
(214, 'Fujitsu General 6.0kW ASTG18LXCA', 2199, 2749, 'aircon', 'Medium-capacity split system with high efficiency rating.', ARRAY['6.0kW cooling','6-star energy','i-See sensor','Inverter','Blue fin','Auto restart'], '/images/aircon-14.svg', 4.7, 89, true, null),
(215, 'Panasonic Aquarea 5.0kW Heat Pump', 3499, 4374, 'aircon', 'Ducted heat pump system for whole-home comfort.', ARRAY['5.0kW heating','Zoned control','Inverter','ECONAVI','Underfloor option','WiFi'], '/images/aircon-15.svg', 4.8, 67, true, 'Heat Pump'),
(216, 'Daikin 10.0kW Ducted System', 5999, 7499, 'aircon', 'Whole-home ducted solution with MyZone smart zoning.', ARRAY['10.0kW cooling','MyZone zoning','Inverter','Smart control','R32','Ultra-thin indoor'], '/images/aircon-16.svg', 4.9, 45, true, 'Ducted'),
(217, 'Mitsubishi Heavy 10.0kW FDTQ', 4799, 5999, 'aircon', 'Ceiling cassette with 3D Auto and wireless remote.', ARRAY['10.0kW cooling','Ceiling cassette','3D Auto','Wireless remote','R32','Self clean'], '/images/aircon-17.svg', 4.7, 34, true, null),
(218, 'Samsung Floor Standing 14kW', 3299, 4124, 'aircon', 'Floor-standing unit for large commercial or residential spaces.', ARRAY['14.0kW cooling','Floor standing','Inverter','Fast cooling','Long reach','WiFi ready'], '/images/aircon-18.svg', 4.6, 56, true, null),
(219, 'Fujitsu General 2.5kW ASTG07LXCA', 899, 1124, 'aircon', 'Ultra-compact split perfect for small bedrooms and studies.', ARRAY['2.5kW cooling','Compact design','Super quiet','Inverter','i-See sensor','R32 gas'], '/images/aircon-19.svg', 4.5, 234, true, null),
(220, 'Porta Air 3.2kW Mobile AC', 599, 749, 'aircon', 'Portable air conditioner — no installation required.', ARRAY['3.2kW cooling','Portable','No install','Dehumidifier','Remote control','Timer'], '/images/aircon-20.svg', 4.1, 389, true, null),
(221, 'Toshiba RAS-1325 3.5kW Split', 1049, 1311, 'aircon', 'Reliable Toshiba split system with Toshiba IAQ technology.', ARRAY['3.5kW cooling','IAQ technology','Inverter','Self cleaning','R32','Sleep mode'], '/images/aircon-21.svg', 4.5, 167, true, null),
(222, 'ActronAir Platinum 7.0kW', 2899, 3624, 'aircon', 'Australian-designed split system built for harsh Aussie conditions.', ARRAY['7.0kW cooling','Aussie designed','Inverter','Turbo mode','R32','Serpent coil'], '/images/aircon-22.svg', 4.7, 98, true, 'Aussie Made'),
(223, 'Braemar Pro Series 5.0kW', 2199, 2749, 'aircon', 'Commercial-grade split system from Australian brand Braemar.', ARRAY['5.0kW cooling','Commercial grade','Inverter','Auto restart','R32','Wide operation range'], '/images/aircon-23.svg', 4.6, 78, true, null),
(224, 'Seeley International Coolair 3.5kW', 1399, 1749, 'aircon', 'Evaporative cooling alternative — energy-efficient and eco-friendly.', ARRAY['3.5kW cooling','Evaporative','Low energy','Fresh air','Eco-friendly','Smart control'], '/images/aircon-24.svg', 4.3, 134, true, null),
(225, 'Breezair Classic Evaporative 7.5kW', 3999, 4999, 'aircon', 'Whole-home evaporative cooler with climate control.', ARRAY['7.5kW cooling','Evaporative','Climate control','Low humidity','Filter system','WiFi ready'], '/images/aircon-25.svg', 4.5, 89, true, 'Eco');

-- Verify
SELECT COUNT(*) AS aircon_products FROM products WHERE category = 'aircon';
